### ISSUE TITLE
how to install openpose?

### ISSUE THREAD

**Issue by aitechguy0105** [Sergey-Mr/VisualSizer-Great-Uni-Hack#1]
I can't find openpose in pyPI.

**Comment by Sergey-Mr** [comment]
Hello, this repository was created purely for the submission at the Hackathon, please refer to another reporsitory 'VisualSizer' to see updates in the project: 
https://github.com/Sergey-Mr/VisualSizer

Concerning the openpose installation, here is the link to the official documentation and guide on installation
https://github.com/CMU-Perceptual-Computing-Lab/openpose

**Comment by Sergey-Mr** [comment]
Hello, this repository was created purely for the submission at the Hackathon, please refer to another reporsitory 'VisualSizer' to see updates in the project: 
https://github.com/Sergey-Mr/VisualSizer

Concerning the openpose installation, here is the link to the official documentation and guide on installation
https://github.com/CMU-Perceptual-Computing-Lab/openpose

**Comment by aitechguy0105** [comment]
thank you for your kind help, you do body measurement with openpose, and
what about using SMPL 3d model?
just say..generate 3d model from images and then do body-part measurement
for clothing?

**Comment by Sergey-Mr** [comment]
Hello, thank you for the interest in the project and your feedback. I am using opnepose because the goal is to make the program run as fast as possible and avoid unnecessary complicatoins.

**Comment by aitechguy0105** [comment]
Merry Christmas! Wishing you and your family a great holiday season.
May your new year be filled with joy, success, and happiness. Cheers!

**Comment by Sergey-Mr** [comment]
Thank you very much! Merry Christmas and prosperous New Year to you and your family!
